### ISSUE TITLE
Backend dies on docker-compose up

### ISSUE THREAD

**Issue by Sshuichi** [rudderlabs/rudder-server#1269]
**Describe the bug**
Backend can't start on docker

**Steps to reproduce the bug**
Docker-compose up 

**Logs** 
```
backend_1        | INFO: No .env file found.
backend_1        | [Config] :: Failed to parse Config Yaml, using default values: open ./config/config.yaml: no such file or directory
db_1             |
db_1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1             |
d-transformer_1  |
d-transformer_1  | > rudder-transformer@0.1.5-rc.0 start /home/node/app
d-transformer_1  | > node destTransformer.js
d-transformer_1  |
db_1             | 2021-09-23 14:20:28.293 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1             | 2021-09-23 14:20:28.293 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1             | 2021-09-23 14:20:28.319 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1             | 2021-09-23 14:20:28.357 UTC [21] LOG:  database system was shut down at 2021-09-23 14:17:39 UTC
db_1             | 2021-09-23 14:20:28.378 UTC [1] LOG:  database system is ready to accept connections
db_1             | 2021-09-23 14:20:28.673 UTC [28] LOG:  incomplete startup packet
backend_1        | [EventSchemas] You are using default password. Please change it by setting env variable RUDDER_ADMIN_PASSWORD
backend_1        | 2021-09-23T14:20:28.696Z	ERROR	transformer/transformer.go:251	Unable to make a transfomer build version call with error : Get http://d-transformer:9090/transformerBuildVersion: dial tcp 172.20.0.3:9090: connect: connection refused
backend_1        | 2021-09-23T14:20:28.696Z	ERROR	stats/stats.go:109	write udp 127.0.0.1:60940->127.0.0.1:8125: write: connection refused
backend_1        | 2021-09-23T14:20:28.696Z	INFO	rudder-server/main.go:138	Suppress User feature is enterprise only. Unable to poll regulations.
backend_1        | 2021-09-23T14:20:28.696Z	INFO	rudder-server/main.go:82	warehousemode embedded
backend_1        | 2021-09-23T14:20:28.697Z	INFO	misc/misc.go:324	RUDDER_TMPDIR not found, falling back to /tmp
backend_1        |
backend_1        | 2021-09-23T14:20:28.697Z	INFO	admin/admin.go:246	Serving on admin interface @ /tmp/rudder-server.sock
backend_1        | 2021-09-23T14:20:28.697Z	INFO	db/embeddedRecovery.go:51	Starting in normal mode
backend_1        | 2021-09-23T14:20:28.697Z	INFO	apphandlers/embeddedAppHandler.go:38	Main starting
backend_1        | 2021-09-23T14:20:28.697Z	ERROR	stats/stats.go:175	write udp 127.0.0.1:59045->127.0.0.1:8125: write: connection refused
db_1             | 2021-09-23 14:20:28.698 UTC [29] FATAL:  password authentication failed for user "rudder"
db_1             | 2021-09-23 14:20:28.698 UTC [29] DETAIL:  Password does not match for user "rudder".
db_1             | 	Connection matched pg_hba.conf line 95: "host all all all md5"
backend_1        | 2021-09-23T14:20:28.699Z	ERROR	rruntime/goroutine-factory.go:42	pq: password authentication failed for user "rudder"
backend_1        | 2021-09-23T14:20:28.699Z	ERROR	rruntime/goroutine-factory.go:42	goroutine 68 [running]:
backend_1        | github.com/rudderlabs/rudder-server/utils/logger.(*LoggerT).Fatal(0xc00019e820, 0xc0009422e0, 0x1, 0x1)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/utils/logger/logger.go:264 +0x10b
backend_1        | github.com/rudderlabs/rudder-server/rruntime.Go.func1.1(0x20c7d20, 0xc0008b4990)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/rruntime/goroutine-factory.go:42 +0x37f
backend_1        | panic(0x18cbe60, 0xc000994120)
backend_1        | 	/root/.goenv/versions/1.13.15/src/runtime/panic.go:679 +0x1b2
backend_1        | github.com/rudderlabs/rudder-server/services/validators.createDBConnection(0xc0008a6b90)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/services/validators/envValidator.go:141 +0x287
backend_1        | github.com/rudderlabs/rudder-server/services/validators.ValidateEnv(0x0)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/services/validators/envValidator.go:165 +0x2e
backend_1        | github.com/rudderlabs/rudder-server/app/apphandlers.rudderCoreBaseSetup()
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/app/apphandlers/setup.go:82 +0x26
backend_1        | github.com/rudderlabs/rudder-server/app/apphandlers.(*EmbeddedApp).StartRudderCore(0xc0008b2240, 0xc0005cf5e0)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/app/apphandlers/embeddedAppHandler.go:40 +0x90
backend_1        | main.main.func4()
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/main.go:173 +0x3e
backend_1        | github.com/rudderlabs/rudder-server/rruntime.Go.func1(0xc0009361d0)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/rruntime/goroutine-factory.go:46 +0x81
backend_1        | created by github.com/rudderlabs/rudder-server/rruntime.Go
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/rruntime/goroutine-factory.go:32 +0x3f
backend_1        |
backend_1        | 2021/09/23 14:20:28 notifying bugsnag: pq: password authentication failed for user "rudder"
backend_1        | 2021/09/23 14:20:28 bugsnag.Notify: bugsnag/payload.deliver: invalid api key: ''
backend_1        | 2021/09/23 14:20:28 bugsnag/sessions/publisher.publish invalid API key: ''
backend_1        | panic: pq: password authentication failed for user "rudder" [recovered]
backend_1        | 	panic: pq: password authentication failed for user "rudder" [recovered]
backend_1        | 	panic: pq: password authentication failed for user "rudder"
backend_1        |
backend_1        | goroutine 68 [running]:
backend_1        | github.com/bugsnag/bugsnag-go.AutoNotify(0xc000a1fad8, 0x3, 0x3)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/vendor/github.com/bugsnag/bugsnag-go/bugsnag.go:109 +0x2bc
backend_1        | panic(0x18cbe60, 0xc000994120)
backend_1        | 	/root/.goenv/versions/1.13.15/src/runtime/panic.go:679 +0x1b2
backend_1        | github.com/rudderlabs/rudder-server/rruntime.Go.func1.1(0x20c7d20, 0xc0008b4990)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/rruntime/goroutine-factory.go:43 +0x39a
backend_1        | panic(0x18cbe60, 0xc000994120)
backend_1        | 	/root/.goenv/versions/1.13.15/src/runtime/panic.go:679 +0x1b2
backend_1        | github.com/rudderlabs/rudder-server/services/validators.createDBConnection(0xc0008a6b90)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/services/validators/envValidator.go:141 +0x287
backend_1        | github.com/rudderlabs/rudder-server/services/validators.ValidateEnv(0x0)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/services/validators/envValidator.go:165 +0x2e
backend_1        | github.com/rudderlabs/rudder-server/app/apphandlers.rudderCoreBaseSetup()
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/app/apphandlers/setup.go:82 +0x26
backend_1        | github.com/rudderlabs/rudder-server/app/apphandlers.(*EmbeddedApp).StartRudderCore(0xc0008b2240, 0xc0005cf5e0)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/app/apphandlers/embeddedAppHandler.go:40 +0x90
backend_1        | main.main.func4()
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/main.go:173 +0x3e
backend_1        | github.com/rudderlabs/rudder-server/rruntime.Go.func1(0xc0009361d0)
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/rruntime/goroutine-factory.go:46 +0x81
backend_1        | created by github.com/rudderlabs/rudder-server/rruntime.Go
backend_1        | 	/codebuild/output/src071433866/src/github.com/rudderlabs/rudder-server/rruntime/goroutine-factory.go:32 +0x3f
d-transformer_1  | Master 20 is running []
d-transformer_1  | Worker 33 is online []
d-transformer_1  | Worker 27 is online []
d-transformer_1  | Worker 39 is online []
d-transformer_1  | Worker 43 is online []
d-transformer_1  | Worker 48 is online []
d-transformer_1  | Worker 55 is online []
d-transformer_1  | Worker 84 is online []
d-transformer_1  | Worker 62 is online []
d-transformer_1  | Worker 69 is online []
d-transformer_1  | Worker 90 is online []
d-transformer_1  | Worker 76 is online []
d-transformer_1  | Worker 92 is online []
d-transformer_1  | Worker 39 started []
d-transformer_1  | Worker 43 started []
d-transformer_1  | Worker 33 started []
d-transformer_1  | Worker 27 started []
d-transformer_1  | Worker 48 started []
d-transformer_1  | Worker 62 started []
d-transformer_1  | Worker 55 started []
d-transformer_1  | Worker 69 started []
d-transformer_1  | Worker 90 started []
d-transformer_1  | Worker 84 started []
d-transformer_1  | Worker 92 started []
d-transformer_1  | Worker 76 started []
tracker_backend_1 exited with code 2
```
docker-compose.yml: 

```
version: "3.7"

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=rudder
      - POSTGRES_PASSWORD=***********
      - POSTGRES_DB=jobsdb
    ports:
      - "6432:5432"
  backend:
    depends_on:
      - db
      - d-transformer
    image: rudderlabs/rudder-server:1-alpine
    entrypoint: sh -c '/wait-for db:5432 -- /rudder-server'
    ports:
      - "6000:8080"
    environment:
      - JOBS_DB_HOST=db
      - JOBS_DB_USER=rudder
      - JOBS_DB_PORT=5432
      - JOBS_DB_DB_NAME=jobsdb
      - JOBS_DB_PASSWORD=***********
      - DEST_TRANSFORM_URL=http://d-transformer:9090
      - CONFIG_BACKEND_URL=https://api.rudderlabs.com
      - WORKSPACE_TOKEN=1wDs1bvti3l9GhAF24LUHUyTaZd
      # - RSERVER_BACKEND_CONFIG_CONFIG_FROM_FILE=true
      # - RSERVER_BACKEND_CONFIG_CONFIG_JSONPATH=<workspace_config_filepath_in_container> # For ex., /etc/rudderstack/workspaceConfig.json
    # Uncomment the following lines to mount workspaceConfig file
    # volumes:
    #   - <absolute_path_to_workspace_config>:<workspace_config_filepath_in_container> # Value for <workspace_config_filepath_in_container> should be same as the value provided for RSERVER_BACKEND_CONFIG_CONFIG_JSONPATH
  d-transformer:
    image: rudderlabs/rudder-transformer:latest
    ports:
      - "9090:9090"
  # minio:
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #   command: server /data
```

Any help is highly appreciated
