### ISSUE TITLE
How to connect rudder-server with aws rds managed database instead of running database on container?

### ISSUE THREAD

**Issue by hisrarul** [rudderlabs/rudder-server#446]
Hi,

I am trying to run the application supported with aws rds managed database. I verified that the aws postgres database is accessible on my machine but when I tried to pass the db endpoint in the environment variable of rudder-docker.yaml. It doesn't seems to work.
```
    entrypoint: sh -c '/wait-for aws-rds-postgres.amazonaws.com:5432 -- /rudder-server'
    ports:
      - "8080:8080"
    environment:
      - JOBS_DB_HOST=aws-rds-postgres.amazonaws.com
      - JOBS_DB_USER=rudder
      - JOBS_DB_PORT=5432
      - JOBS_DB_DB_NAME=jobsdb
      - JOBS_DB_PASSWORD=password
```

Please suggest what I need to do in order to run it in docker or kubernetes?
